---
title: "show_colors"
author: "muscle"
date: "2018年11月12日"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Extending ggplot2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>", fig.width = 7, fig.height = 7, fig.align = "center")
library(scales)
```

介绍获取色彩的一些途径。

## 1 系统调色板

```{r cars}
n <- 10
rainbow(n, s = 1, v = 1, start = 0, end = max(1, n - 1)/n, alpha = 1)
heat.colors(n, alpha = 1)
terrain.colors(n, alpha = 1)
topo.colors(n, alpha = 1)
cm.colors(n, alpha = 1)

```

### 1.1 绘制基础调色板

```{r pressure, echo=FALSE}
library(scales)
show_col(rainbow(10),labels = T)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

### 1.2 创建调色板

```{r}
oblue <- colorRampPalette(c("orange", "blue"))
show_col(oblue(10),labels = T)
```

```{r}
n <- 200
temp.col <- oblue(n)
par(mar = c(0.5,0.5,2,0.5))
barplot(rep(1,times = n),col = temp.col, border = temp.col, horiz = F, axes = FALSE)

```


### 1.3 系统命名色彩
系统本身提供了657种命名色彩，通过colors()函数，可以获取名称。

```{r}
head(colors(), 12)
```

绘制所有色彩如下：
```{r}
show_col(colours(), labels = F)
```


## 2 RColorBrewer

```{r}
library(RColorBrewer)
```


### 2.1 ColorBrewer调色板
所有调色板
```{r eval=FALSE }
display.brewer.all(type = "all")
```

单色系渐变
```{r}
display.brewer.all(type = "seq")  

```

双色系渐变
```{r}
display.brewer.all(type = "div")  
```


离散色系
```{r}
display.brewer.all(type = "qual")  
```


### 2.2 获取颜色
离散颜色
```{r}
cols <- brewer_pal(palette = "Greens")(5)
cols
```

基于离散颜色，创建连续颜色
```{r}
cols <- brewer_pal("div")(5)
show_col(gradient_n_pal(cols)(seq(0, 1, length.out = 30)))

```

